import { VIKING } from '../../catalog/buildings.js';

/** The per-tribe personal-name pools; the grid math that turns an entity id into a name lives next door. */

/** A tribe's given names, split by the sex of the body a settler draws. */
export interface NamePool {
  /** Male given names, and the source of patronymic roots. */
  readonly male: readonly string[];
  readonly female: readonly string[];
}

/**
 * Hand-authored Old Norse given names, split by sex to match the drawn body. The original game carries
 * none of these, so the list is an independent approximation drawn from historical Norse name lists. The
 * male pool is larger because male settlers outnumber female ones, so more of them need distinct names.
 */
const VIKING_NAMES: NamePool = {
  male: [
    'Ragnar',
    'Bjørn',
    'Leif',
    'Sten',
    'Ivar',
    'Ulf',
    'Harald',
    'Sigurd',
    'Knut',
    'Torstein',
    'Halfdan',
    'Egil',
    'Gunnar',
    'Rollo',
    'Sven',
    'Arne',
    'Vidar',
    'Erik',
    'Hakon',
    'Frode',
    'Orm',
    'Toke',
    'Vali',
    'Asger',
    'Grim',
    'Kettil',
    'Vagn',
    'Hemming',
    'Ottar',
    'Rurik',
    'Guthorm',
    'Sigtrygg',
    'Thorvald',
    'Thorolf',
    'Ospak',
    'Hallstein',
    'Ingolf',
    'Floki',
    'Ubbe',
    'Hastein',
    'Njal',
    'Skarde',
    'Gorm',
    'Thrand',
    'Onund',
    'Steinar',
    'Hallvard',
    'Kolbein',
    'Eystein',
    'Ozur',
    'Amund',
    'Trygve',
    'Snorri',
    'Yngvar',
    'Dag',
    'Alrek',
    'Hrolf',
    'Sigmund',
    'Bo',
    'Refil',
    'Eskil',
    'Bergthor',
    'Kolgrim',
    'Thorgils',
    'Audun',
    'Birger',
    'Brand',
    'Eindride',
    'Finn',
    'Geir',
    'Gisli',
    'Grettir',
    'Haki',
    'Hallbjorn',
    'Hauk',
    'Ingimar',
    'Jorund',
    'Kari',
    'Kjartan',
    'Kveldulf',
    'Magnus',
    'Mord',
    'Odd',
    'Ofeig',
    'Ragnvald',
    'Roar',
    'Sigvat',
    'Skallagrim',
    'Solmund',
    'Starkad',
    'Sumarlidi',
    'Thorbjorn',
    'Thorfinn',
    'Thorgrim',
    'Thorir',
    'Thorkell',
    'Torgeir',
    'Ulfar',
    'Vemund',
    'Vestein',
    'Yngvi',
  ],
  female: [
    'Astrid',
    'Freya',
    'Sigrid',
    'Ingrid',
    'Helga',
    'Gunnhild',
    'Thyra',
    'Solveig',
    'Ragnhild',
    'Bodil',
    'Hilde',
    'Yrsa',
    'Signe',
    'Gudrun',
    'Liv',
    'Randi',
    'Tove',
    'Estrid',
    'Runa',
    'Alfhild',
    'Thora',
    'Ragna',
    'Ingeborg',
    'Gyda',
    'Aslaug',
    'Bergljot',
    'Dagny',
    'Eir',
    'Frida',
    'Gerd',
    'Groa',
    'Halldis',
    'Herdis',
    'Hervor',
    'Jofrid',
    'Kelda',
    'Ljufa',
    'Nanna',
    'Oddny',
    'Ragnfrid',
    'Saga',
    'Sunniva',
    'Svanhild',
    'Thurid',
    'Torhild',
    'Ulfhild',
    'Unn',
    'Vigdis',
    'Yngvild',
    'Aud',
    'Bera',
    'Borghild',
    'Disa',
    'Eldrid',
    'Gunnvor',
    'Hallgerd',
    'Idunn',
    'Jorunn',
    'Katla',
    'Ljot',
    'Ragnborg',
    'Signy',
    'Thordis',
    'Vilborg',
    'Asa',
    'Bothild',
    'Geirlaug',
    'Holmfrid',
    'Ingrun',
    'Osk',
    'Thorgunna',
    'Yr',
  ],
};

export const NAME_POOLS: Readonly<Record<number, NamePool>> = {
  [VIKING]: VIKING_NAMES,
};

/** The pool for a tribe that has none of its own. */
export const FALLBACK_POOL = VIKING_NAMES;
