import { VIKING } from '../../catalog/buildings.js';

/**
 * The per-tribe personal-name pools {@link import('../character-names.js').characterName} draws from. Data
 * only — the grid math that turns an entity id into a name stays in `game/character-names.ts`.
 */

/** A tribe's given names, split by the sex of the body a settler draws. */
export interface NamePool {
  /** Male given names. Also the source of patronymic roots (a father's name is a male given name). */
  readonly male: readonly string[];
  /** Female given names. */
  readonly female: readonly string[];
}

/**
 * Hand-authored Old Norse given names, split by sex to match the drawn body. Drawn from common historical
 * Norse name lists; the original game carries none of these, so this is an independent approximation, not
 * extracted content.
 *
 * With the surname cross product (see {@link characterName}) these give 101 × 101 = 10 201 distinct male
 * full names and 72 × 101 = 7 272 female ones. The male pool is the larger because male settlers heavily
 * outnumber female ones, so more of them need distinct names; both counts sit far past any real settlement,
 * so a repeat is very rare.
 */
const VIKING_NAMES: NamePool = {
  male: [
    'Ragnar',
    'Bjørn',
    'Leif',
    'Sten',
    'Ivar',
    'Ulf',
    'Harald',
    'Sigurd',
    'Knut',
    'Torstein',
    'Halfdan',
    'Egil',
    'Gunnar',
    'Rollo',
    'Sven',
    'Arne',
    'Vidar',
    'Erik',
    'Hakon',
    'Frode',
    'Orm',
    'Toke',
    'Vali',
    'Asger',
    'Grim',
    'Kettil',
    'Vagn',
    'Hemming',
    'Ottar',
    'Rurik',
    'Guthorm',
    'Sigtrygg',
    'Thorvald',
    'Thorolf',
    'Ospak',
    'Hallstein',
    'Ingolf',
    'Floki',
    'Ubbe',
    'Hastein',
    'Njal',
    'Skarde',
    'Gorm',
    'Thrand',
    'Onund',
    'Steinar',
    'Hallvard',
    'Kolbein',
    'Eystein',
    'Ozur',
    'Amund',
    'Trygve',
    'Snorri',
    'Yngvar',
    'Dag',
    'Alrek',
    'Hrolf',
    'Sigmund',
    'Bo',
    'Refil',
    'Eskil',
    'Bergthor',
    'Kolgrim',
    'Thorgils',
    'Audun',
    'Birger',
    'Brand',
    'Eindride',
    'Finn',
    'Geir',
    'Gisli',
    'Grettir',
    'Haki',
    'Hallbjorn',
    'Hauk',
    'Ingimar',
    'Jorund',
    'Kari',
    'Kjartan',
    'Kveldulf',
    'Magnus',
    'Mord',
    'Odd',
    'Ofeig',
    'Ragnvald',
    'Roar',
    'Sigvat',
    'Skallagrim',
    'Solmund',
    'Starkad',
    'Sumarlidi',
    'Thorbjorn',
    'Thorfinn',
    'Thorgrim',
    'Thorir',
    'Thorkell',
    'Torgeir',
    'Ulfar',
    'Vemund',
    'Vestein',
    'Yngvi',
  ],
  female: [
    'Astrid',
    'Freya',
    'Sigrid',
    'Ingrid',
    'Helga',
    'Gunnhild',
    'Thyra',
    'Solveig',
    'Ragnhild',
    'Bodil',
    'Hilde',
    'Yrsa',
    'Signe',
    'Gudrun',
    'Liv',
    'Randi',
    'Tove',
    'Estrid',
    'Runa',
    'Alfhild',
    'Thora',
    'Ragna',
    'Ingeborg',
    'Gyda',
    'Aslaug',
    'Bergljot',
    'Dagny',
    'Eir',
    'Frida',
    'Gerd',
    'Groa',
    'Halldis',
    'Herdis',
    'Hervor',
    'Jofrid',
    'Kelda',
    'Ljufa',
    'Nanna',
    'Oddny',
    'Ragnfrid',
    'Saga',
    'Sunniva',
    'Svanhild',
    'Thurid',
    'Torhild',
    'Ulfhild',
    'Unn',
    'Vigdis',
    'Yngvild',
    'Aud',
    'Bera',
    'Borghild',
    'Disa',
    'Eldrid',
    'Gunnvor',
    'Hallgerd',
    'Idunn',
    'Jorunn',
    'Katla',
    'Ljot',
    'Ragnborg',
    'Signy',
    'Thordis',
    'Vilborg',
    'Asa',
    'Bothild',
    'Geirlaug',
    'Holmfrid',
    'Ingrun',
    'Osk',
    'Thorgunna',
    'Yr',
  ],
};

/** Name pools by tribe. Add a faction here to give its settlers faction-appropriate names. */
export const NAME_POOLS: Readonly<Record<number, NamePool>> = {
  [VIKING]: VIKING_NAMES,
};

/** The pool used for a tribe that has no pool of its own yet — the only content tribe today is viking. */
export const FALLBACK_POOL = VIKING_NAMES;
