import './melee-engagement/autonomous.cases.js';
import './melee-engagement/attack-move.cases.js';
import './melee-engagement/animal-order.cases.js';
import './melee-engagement/attack-order.cases.js';
import './melee-engagement/battle-alert.cases.js';
import './melee-engagement/economy-gate.cases.js';
import './melee-engagement/move-order.cases.js';
import './melee-engagement/needs-gate.cases.js';
import './melee-engagement/sealed-target.cases.js';
