import { Texture, TextureSource } from 'pixi.js';
import { expect, it } from 'vitest';
import { PalettedSprite } from '../../src/gpu/paletted-sprite/index.js';
import { createPooled } from '../../src/gpu/sprite-pool/pooled-entity.js';
import { SelectionEffects } from '../../src/gpu/sprite-pool/selection-effects.js';
import { SelectionSprite } from '../../src/gpu/sprite-selection-effect.js';
import { TextureCache } from '../../src/gpu/texture-cache.js';
import { syntheticHumanLut } from '../support/human-palettes.js';
import { useHeadlessShaderContext } from '../support/shader-context.js';

it('outlines the visible body, excludes shadows, and releases stamps when the style changes', () => {
  const textures = new TextureCache();
  const effects = new SelectionEffects(textures);
  const pe = createPooled('building', undefined);
  if (pe.paletted) throw new Error('Expected a plain building');
  const body = new SelectionSprite(Texture.WHITE);
  body.position.set(12, -30);
  body.scale.set(2);
  const shadow = new SelectionSprite(Texture.WHITE);
  pe.sprites.push(shadow, body);
  pe.pickExempt.push(true, false);
  pe.container.addChild(shadow, body);
  effects.update(pe, 'outline', 1, 0);
  const outline = pe.container.children[0];
  expect(outline?.children).toHaveLength(16);
  expect(outline?.children[0]?.position.x).toBeCloseTo(14);
  expect(outline?.children[0]?.scale.x).toBe(2);
  const dark = outline?.children[0];
  const ivory = outline?.children[8];
  expect(dark).toBeInstanceOf(SelectionSprite);
  expect(ivory).toBeInstanceOf(SelectionSprite);
  if (!(dark instanceof SelectionSprite) || !(ivory instanceof SelectionSprite))
    throw new Error('Missing outline');
  expect(dark.tint).toBe(0x14211b);
  expect(ivory.tint).toBe(0xf2e8c9);
  expect(ivory.position.x).toBeCloseTo(13.25);
  effects.update(pe, 'outline', 2, 0);
  expect(pe.container.children[0]).toBe(outline);
  expect(outline?.children[0]?.position.x).toBeCloseTo(13);
  effects.setVisible(false);
  expect(outline?.visible).toBe(false);
  effects.setVisible(true);
  expect(outline?.visible).toBe(true);
  effects.update(pe, 'pulse', 2, 0.45);
  expect(outline?.destroyed).toBe(true);
  expect(shadow.selectionEffect).toBe(0);
  expect(body.selectionEffect).toBeCloseTo(0.095);
  effects.setVisible(false);
  expect(body.selectionEffect).toBe(0);
  effects.setVisible(true);
  expect(body.selectionEffect).toBeCloseTo(0.095);
  effects.update(pe, 'pulse', 2, 1.35);
  expect(body.selectionEffect).toBeCloseTo(0.045);
  effects.clear(pe);
  expect(body.selectionEffect).toBe(0);
  expect(pe.container.children).toEqual([shadow, body]);
  pe.container.destroy({ children: true });
  textures.clear();
});

useHeadlessShaderContext();

it('keeps vehicle outlines out of linear atlas sampling and follows mesh origin and shear', () => {
  const textures = new TextureCache();
  const effects = new SelectionEffects(textures);
  const lut = syntheticHumanLut();
  const pe = createPooled('vehicle', lut);
  if (!pe.paletted) throw new Error('Expected an indexed vehicle');
  const source = new TextureSource({ width: 32, height: 32, scaleMode: 'nearest' });
  const body = new PalettedSprite(lut.source, lut.colours);
  body.setFrame(source, { x: 0, y: 0, width: 16, height: 24, offsetX: -8, offsetY: -24 }, 32, 32);
  body.artScale = 2;
  body.artDx = 3;
  body.artDy = 4;
  body.shear = 0.1;
  pe.sprites.push(body);
  pe.container.addChild(body);
  effects.update(pe, 'outline', 0.75, 0);
  expect(textures.pageSources().has(source)).toBe(false);
  const outline = pe.container.children[0];
  const stamp = outline?.children[0];
  expect(stamp?.position.x).toBeCloseTo(3 + (-8 - 2.4) * 2 + 2 / 0.75);
  expect(stamp?.position.y).toBeCloseTo(4 - 24 * 2);
  stamp?.updateLocalTransform();
  expect(stamp?.localTransform.c).toBeCloseTo(0.2);
  effects.clear(pe);
  pe.container.destroy({ children: true });
  textures.clear();
  source.destroy();
  lut.source.destroy();
});
