import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { loadRealContent } from '../../src/content/real-content.js';
import { hasRealIr, irPath } from './helpers.js';

/**
 * `loadRealContent` over the REAL ir.json under test — the full-parse and memoization halves of the
 * loader's contract. The degrade (absent → null) and malformed (throw) paths run unconditionally
 * over synthetic responses in the fixture suite (`test/real-content.test.ts`); this file needs the
 * generated bytes. The loader takes an injectable `fetch`, driven here over Node fs.
 */

/** A `fetch` that serves the IR under test off disk for the one URL the loader requests. */
const fsFetch: typeof fetch = (input) => {
  if (String(input) !== '/ir.json') return Promise.resolve(new Response(null, { status: 404 }));
  return Promise.resolve(new Response(readFileSync(irPath(), 'utf8')));
};

describe.runIf(hasRealIr())('loadRealContent over the real IR', () => {
  it('parses the full real content set from ir.json', async () => {
    const set = await loadRealContent(fsFetch);
    expect(set).not.toBeNull();
    // Counts verified against the pipeline output on 2026-07-14; a schema skew would drop rows or throw.
    expect(set?.goods).toHaveLength(65);
    expect(set?.buildings).toHaveLength(55);
    expect(set?.jobs).toHaveLength(55);
    expect(set?.tribes).toHaveLength(41);
  });

  // The no-arg (global-fetch) path is the one the app uses; the injected-fetch tests bypass its
  // memo, so exercise it directly here: a failed load must not pin null, and success is cached.
  it('memoizes the default-fetch path and retries after a failed load', async () => {
    let fetches = 0;
    vi.stubGlobal('fetch', () => {
      fetches++;
      return Promise.resolve(new Response(null, { status: 503 }));
    });
    expect(await loadRealContent()).toBeNull();

    const ir = readFileSync(irPath(), 'utf8');
    vi.stubGlobal('fetch', () => {
      fetches++;
      return Promise.resolve(new Response(ir));
    });
    const first = await loadRealContent();
    const second = await loadRealContent();
    expect(first).not.toBeNull();
    expect(second).toBe(first); // served from the memo, not re-fetched or re-parsed
    expect(fetches).toBe(2); // the failed load retried once; the third call hit the memo

    vi.unstubAllGlobals();
  });
});
