/** The `*Html` entries are assigned to innerHTML: trusted markup only, never interpolated input. */
export const en = {
  setup: {
    title: 'Open Northland - first-run setup',
    introHtml:
      'Open Northland is a free re-implementation of <em>Cultures - 8th Wonder of the World</em>. It ' +
      'ships no game art or sounds: on this first run it converts the assets of your own copy of the ' +
      'original game into its data folder. Select the folder your game is installed in (the one with ' +
      '<code>Game.exe</code> and <code>DataX</code>) to begin.',
    pathPlaceholder: 'Path to your Cultures 8th Wonder folder…',
    dropPrompt: 'Drop your Cultures 8th Wonder folder here',
    browserStorage: "this browser's private storage",
    browse: 'Browse…',
    readingFolder: 'Reading the folder…',
    detected: 'Found on this computer:',
    install: 'Install game content',
    regenerate: 'Regenerate game content',
    play: 'Play',
    playAnyway: 'Play anyway',
    cancel: 'Cancel',
    back: 'Back',
    installed: 'Game content installed.',
    legalHtml:
      'Your original game files are only read, never modified. The converted data stays on this ' +
      'computer in <code id="data-root"></code>.',
    probe: {
      withMod: 'Game found (with the CulturesNation mod).',
      externalMod: 'Game found. Using the CulturesNation mod from {path}.',
      noMod: 'Game found - but the CulturesNation mod is missing.',
      noArchives: 'No game archives (.lib) found there - pick the folder that contains Game.exe and DataX.',
    },
    status: {
      ready: 'Game content is installed. Regenerate it here if you want a fresh conversion.',
      staleRevision:
        'Your game content is incomplete or was generated by an older version of Open Northland - ' +
        'regenerating it is recommended.',
      staleSchema:
        'Your game content was generated by an incompatible older version of Open Northland - it must ' +
        'be regenerated before playing.',
    },
    run: {
      starting: 'Starting…',
      files: '{done} files',
      failed: 'Installing the game content failed.',
    },
    stages: {
      unpack: 'Unpacking game archives',
      pictures: 'Converting pictures',
      atlases: 'Building sprite atlases',
      'player-colors': 'Building player colours',
      gui: 'Converting the interface art',
      fonts: 'Converting fonts',
      goods: 'Converting goods icons',
      ir: 'Extracting game rules',
      transitions: 'Composing terrain transitions',
      maps: 'Decoding maps',
      music: 'Rendering the soundtrack',
    },
    mod: {
      requiredUpstreamHtml:
        'The free community mod <strong>CulturesNation</strong> is required to play, and your game ' +
        'folder does not have it. Open Northland can download it for you (~600 MB, from ' +
        "<code>culturesnation.pl</code>'s Google Drive link) into its data folder - your game folder " +
        'stays untouched.',
      requiredOriginHtml:
        'The free community mod <strong>CulturesNation</strong> is required to play, and your game ' +
        'folder does not have it. Open Northland can download it for you (~600 MB, from this site) ' +
        "into this browser's storage - your game folder stays untouched.",
      download: 'Download the mod',
      haveIt: 'I already have it…',
      downloading: 'Downloading the mod…',
      unpacking: 'Unpacking…',
      cancelled: 'Download cancelled.',
      downloadFailed: 'Downloading the mod failed: {message} - {fallback}',
      pickFailed: '{message} - {fallback}',
      fallbackFolder:
        'You can download the mod yourself from culturesnation.pl (news page → CnMod), unpack the zip, ' +
        'and point "I already have it…" at the unpacked folder.',
      fallbackArchive:
        'You can download the mod yourself from culturesnation.pl (news page → CnMod) and point ' +
        '"I already have it…" at the downloaded zip file.',
    },
    language: {
      english: 'English',
      polish: 'Polish',
    },
  },
  dialogs: {
    pickGameTitle: 'Select your Cultures - 8th Wonder of the World folder',
    pickModTitle: 'Select the unpacked CulturesNation mod folder',
    saveGameTitle: 'Save to file',
    loadGameTitle: 'Load a saved game',
    saveFileFilter: 'Open Northland save',
    leaveGame: 'Leave game',
    stay: 'Stay',
    leaveGameMessage: 'Leave the running game?',
    leaveGameDetail: 'Unsaved progress will be lost - you can save from the in-game menu first.',
  },
  menu: {
    game: 'Game',
    reinstall: 'Reinstall game content…',
    openDataFolder: 'Open data folder',
  },
  errors: {
    modStillDownloading: 'the mod is still downloading - wait for it to finish',
    noArchives: 'no game archives (.lib) found under the selected folder',
    modRequired:
      'the CulturesNation mod is required - download it below, or point the wizard at an unpacked copy',
    modDownloadRunning: 'mod download already running',
    noDataCnmd: 'no DataCnmd/ found there - pick the unpacked mod folder (download it from {url})',
    incompatibleSchema: 'content was generated for an incompatible schema - regenerate it first',
    contentMissing: 'there is no converted game content yet - install it first',
    noServiceWorker:
      'this browser will not run a service worker for this site, so the converted game content ' +
      'cannot be served. Private and incognito windows usually block it - try a normal window.',
    noStorage:
      'this browser gives the site no private storage, so there is nowhere to put the converted ' +
      'game content.',
    storageFull:
      'the browser ran out of storage for this site before the conversion finished. Free some disk ' +
      'space and start the installation again.',
    notEnoughStorage:
      'the conversion needs about {needed} GB of browser storage and only {available} GB is ' +
      'available for this site. Free some disk space and reload.',
    conversionElsewhere: 'another tab of this site is already converting - finish or close it first',
    modInstallElsewhere: 'the mod is already being installed - finish that first',
    modArchiveUnavailable: 'this site did not serve the mod archive ({status})',
    pipelineRunning: 'a conversion is already running',
    pipelineWorkerCrashed: 'the converter stopped unexpectedly - reload the page and try again',
    notAFolder: 'that is a file, not a folder - drop the folder your game is installed in',
    setupFailed: 'the installer could not start: {message}',
  },
} as const;

type DeepStrings<T> = { readonly [K in keyof T]: T[K] extends string ? string : DeepStrings<T[K]> };

export type Messages = DeepStrings<typeof en>;
