// Auto-drafted then hand-maintained. This file is the checked-in metadata map from GUI-atlas frame
// index -> semantic meaning for `ls_gui_window.bmd` (the in-game HUD sheet; 193 bobs, firstBobId=0 so a
// gfx-id in the original engine equals the atlas frame index directly). It exists so app HUD code refers
// to UI sprites by name, never by a magic frame number.
//
// Identification basis (per-frame `source`):
//   'manual'      — a project-maintained mapping of frame, rectangle, and HUD purpose. Recheck it
//                   against the running original when exact UI behavior matters.
//   'montage'     — identified by eye from a numbered render of every frame (the labeled-montage technique).
//                   Once a human confirms the category and the glyph is legible, the frame carries a
//                   provisional descriptive name (a read of the drawn glyph, refine-able later); a frame
//                   whose glyph is unread stays `unknown_NNN` with a best-guess `role`/`note`. See
//                   docs/formats/GRAPHICS.md.
//   'unknown'     — not yet identified at all.
//
// The round wooden radial buttons at frames 96–136 were identified visually. Their `order_*` names
// remain provisional until each command is confirmed in the running original.
import type { GuiPaletteName } from './gui-gfx.js';

/** Total bob count of `ls_gui_window.bmd` (decoded from the sheet; firstBobId=0 so ids are 0..192). */
export const GUI_ATLAS_FRAME_COUNT = 193;

/** What a frame is used for. A coarse category so callers can group frames without knowing each name. */
export type GuiFrameRole =
  | 'window_chrome' // 9-slice window border pieces (corners, edges)
  | 'window_bg' // large parchment window backgrounds
  | 'window_control' // titlebar / minimize / maximize / close widgets
  | 'panel' // the left tool-panel background strip
  | 'tool_button' // a left-panel main button (buildings, diplomacy, ...)
  | 'speed_button' // the game-speed button + its state variants
  | 'message_priority' // the message-priority frame + button states
  | 'overview_toggle' // the minimap / world-overview toggle button
  | 'order_icon' // a command/action-order icon (drawn through the 'context' palette)
  | 'resource_icon' // a good / resource glyph
  | 'bar' // a progress / hit / status bar frame
  | 'note' // a pinned parchment note / scroll
  | 'scroll_arrow' // a directional / map-scroll arrow
  | 'decoration' // a flag, ornament, or other chrome
  | 'unknown'; // not yet categorized

/** Where a frame's identification comes from — see the file header. */
export type GuiFrameSource = 'manual' | 'montage' | 'unknown';

/** One GUI-atlas frame's metadata. `name` is unique across the sheet; unidentified frames are `unknown_NNN`. */
export interface GuiFrameMeta {
  /** Unique semantic name, or `unknown_NNN` (zero-padded index) if not yet identified. */
  readonly name: string;
  readonly role: GuiFrameRole;
  /** Best-guess GUI palette (a {@link GuiPaletteName}) this frame is coloured through. */
  readonly palette: GuiPaletteName;
  readonly source: GuiFrameSource;
  /** Names of alternate-state frames for this element (e.g. the speed button's x2/x3/paused frames). */
  readonly states?: readonly string[];
  /** Free-text provenance / glyph description. */
  readonly note?: string;
}

/**
 * Every frame of the GUI-window sheet, indexed by atlas frame id (array index === frame index === original
 * gfx id). Total over the sheet: exactly {@link GUI_ATLAS_FRAME_COUNT} entries, every one named (or
 * `unknown_NNN`), no duplicate names — enforced by `gui-atlas-map.test.ts`.
 */
export const GUI_FRAMES: readonly GuiFrameMeta[] = [
  /* 000 0x00 */ {
    name: 'knot_corner_bl',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: 'rope-knot window corner 7x7 (bottom pair) — orientation provisional; pending the step-3 human pass',
  },
  /* 001 0x01 */ {
    name: 'knot_corner_br',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: 'rope-knot window corner 7x7 (bottom pair) — orientation provisional; pending the step-3 human pass',
  },
  /* 002 0x02 */ {
    name: 'knot_corner_tl',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: 'rope-knot window corner 10x10 (top pair) — orientation provisional; pending the step-3 human pass',
  },
  /* 003 0x03 */ {
    name: 'knot_corner_tr',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: 'rope-knot window corner 10x10 (top pair) — orientation provisional; pending the step-3 human pass',
  },
  /* 004 0x04 */ {
    name: 'unknown_004',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window border: horizontal edge 128x3',
  },
  /* 005 0x05 */ {
    name: 'window_border_bottom',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window border: horizontal edge 128x3 — orientation provisional (details-panel rope-tiling reads coherently); pending the step-3 human pass',
  },
  /* 006 0x06 */ {
    name: 'window_border_right',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window border: vertical edge 3x128 — orientation provisional; pending the step-3 human pass',
  },
  /* 007 0x07 */ {
    name: 'window_border_top',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window border: horizontal edge 128x3 — orientation provisional; pending the step-3 human pass',
  },
  /* 008 0x08 */ {
    name: 'window_border_left',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window border: vertical edge 3x128 — orientation provisional; pending the step-3 human pass',
  },
  /* 009 0x09 */ {
    name: 'corner_5x5_0',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '5x5 corner piece — unconsumed since the rope border landed (frames 0-3 are the window corners); identity pending the step-3 human pass',
  },
  /* 010 0x0a */ {
    name: 'corner_5x5_1',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '5x5 corner piece — unconsumed since the rope border landed (frames 0-3 are the window corners); identity pending the step-3 human pass',
  },
  /* 011 0x0b */ {
    name: 'corner_5x5_2',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '5x5 corner piece — unconsumed since the rope border landed (frames 0-3 are the window corners); identity pending the step-3 human pass',
  },
  /* 012 0x0c */ {
    name: 'corner_5x5_3',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '5x5 corner piece — unconsumed since the rope border landed (frames 0-3 are the window corners); identity pending the step-3 human pass',
  },
  /* 013 0x0d */ {
    name: 'unknown_013',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window-border piece (corner/edge)',
  },
  /* 014 0x0e */ {
    name: 'unknown_014',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window-border piece (corner/edge)',
  },
  /* 015 0x0f */ {
    name: 'unknown_015',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window-border piece (corner/edge)',
  },
  /* 016 0x10 */ {
    name: 'unknown_016',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window-border piece (corner/edge)',
  },
  /* 017 0x11 */ {
    name: 'unknown_017',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'framed box / titlebar widget (~33x33)',
  },
  /* 018 0x12 */ {
    name: 'unknown_018',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'dark ore/coal lump',
  },
  /* 019 0x13 */ {
    name: 'unknown_019',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'framed box / titlebar widget (~33x33)',
  },
  /* 020 0x14 */ {
    name: 'unknown_020',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'framed box / titlebar widget (~33x33)',
  },
  /* 021 0x15 */ {
    name: 'unknown_021',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small pennant / flag',
  },
  /* 022 0x16 */ {
    name: 'unknown_022',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small pennant / flag',
  },
  /* 023 0x17 */ {
    name: 'unknown_023',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small pennant / flag',
  },
  /* 024 0x18 */ {
    name: 'unknown_024',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: '9-slice window-border piece (corner)',
  },
  /* 025 0x19 */ {
    name: 'unknown_025',
    role: 'window_bg',
    palette: 'papyrus',
    source: 'montage',
    note: 'large papyrus window background 610x549',
  },
  /* 026 0x1a */ {
    name: 'unknown_026',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'crossed tool / pick',
  },
  /* 027 0x1b */ {
    name: 'unknown_027',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'pill / capsule',
  },
  /* 028 0x1c */ {
    name: 'unknown_028',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'tool / gear',
  },
  /* 029 0x1d */ {
    name: 'resource_icon_dark_lump',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'dark lump (details-panel stock guess for mud/clay); pending the step-3 human pass',
  },
  /* 030 0x1e */ {
    name: 'resource_icon_round_stone',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'round stone / coal (details-panel stock guess for stone); pending the step-3 human pass',
  },
  /* 031 0x1f */ {
    name: 'unknown_031',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'two-figure glyph',
  },
  /* 032 0x20 */ {
    name: 'unknown_032',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'house / building',
  },
  /* 033 0x21 */ {
    name: 'unknown_033',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'ring / wreath',
  },
  /* 034 0x22 */ {
    name: 'unknown_034',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'gem / diamond',
  },
  /* 035 0x23 */ {
    name: 'unknown_035',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'bird / eagle',
  },
  /* 036 0x24 */ {
    name: 'unknown_036',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'bell / anvil',
  },
  /* 037 0x25 */ {
    name: 'resource_icon_water_drop',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'water drop — used as the Magazyn "Napoje" (drinks) category-tab glyph',
  },
  /* 038 0x26 */ {
    name: 'unknown_038',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small dot / stud',
  },
  /* 039 0x27 */ {
    name: 'unknown_039',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'flag on pole',
  },
  /* 040 0x28 */ {
    name: 'unknown_040',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'coin / disc',
  },
  /* 041 0x29 */ {
    name: 'unknown_041',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'compass / map framed icon ~33x33',
  },
  /* 042 0x2a */ {
    name: 'tool_button_buildings',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2a, rect (0,41,40x35), str 2 "opens buildings menu", msg 0xf3e',
  },
  /* 043 0x2b */ {
    name: 'tool_button_population',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2b, rect (0,204,40x35), str 6 "opens subjects window", msg 0xf40',
  },
  /* 044 0x2c */ {
    name: 'tool_button_diplomacy',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2c, rect (0,151,40x35), str 4 "opens diplomacy window", msg 0xf3f',
  },
  /* 045 0x2d */ {
    name: 'tool_button_extras',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2d, rect (0,73,40x35), str 5 "opens extras window", msg 0xf3d',
  },
  /* 046 0x2e */ {
    name: 'tool_button_mission',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2e, rect (0,117,40x35), str 3 "opens mission window", msg 0xf42',
  },
  /* 047 0x2f */ {
    name: 'tool_button_options',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x2f, rect (0,295,40x35), str 1 "opens options menu", msg 0xf3c',
  },
  /* 048 0x30 */ {
    name: 'tool_button_help',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x30, rect (0,329,40x35), str 0 "opens help window", msg 0xf44',
  },
  /* 049 0x31 */ {
    name: 'speed_button',
    role: 'speed_button',
    palette: 'iconsleft',
    source: 'manual',
    states: ['speed_button_x2', 'speed_button_x3', 'speed_button_paused'],
    note: 'gfx 0x31 _btnSpeed, rect (0,373,40x35), msg 0xf46, tooltip str 0x0D "game speed"; base state (x1/MAX)',
  },
  /* 050 0x32 */ {
    name: 'tool_button_statistics',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x32, rect (0,176,40x35), str 7 "opens statistics window", msg 0xf41',
  },
  /* 051 0x33 */ {
    name: 'tool_panel_background',
    role: 'panel',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x33 CBaseToolGfxElement _toolBackground, rect (0,10,50x433), palette iconsleft',
  },
  /* 052 0x34 */ {
    name: 'speed_button_x2',
    role: 'speed_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x34, speed state speedFactor==2',
  },
  /* 053 0x35 */ {
    name: 'speed_button_x3',
    role: 'speed_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x35, speed state speedFactor==3',
  },
  /* 054 0x36 */ {
    name: 'speed_button_paused',
    role: 'speed_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x36, speed state speedFactor==0 (paused)',
  },
  /* 055 0x37 */ {
    name: 'minimap_frame',
    role: 'window_chrome',
    palette: 'frame',
    source: 'montage',
    note: 'braided minimap/overview window frame 149x133: braid along top+right only, hole flush to the LEFT and BOTTOM edges — drawn pinned to the screen bottom-left corner; measured inner map area (0,16,116x117), near-black opaque',
  },
  /* 056 0x38 */ {
    name: 'tool_button_tech_tree',
    role: 'tool_button',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x38, rect (0,238,40x35), str 8 "opens tech tree", msg 0xf43',
  },
  /* 057 0x39 */ {
    name: 'unknown_057',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'windows / cascade icon',
  },
  /* 058 0x3a */ {
    name: 'unknown_058',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'circle with minus (minimize?)',
  },
  /* 059 0x3b */ {
    name: 'unknown_059',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'circle with plus (maximize?)',
  },
  /* 060 0x3c */ {
    name: 'unknown_060',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'round emblem button, 3 near-identical (button states?)',
  },
  /* 061 0x3d */ {
    name: 'unknown_061',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'round emblem button, 3 near-identical (button states?)',
  },
  /* 062 0x3e */ {
    name: 'unknown_062',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'round emblem button, 3 near-identical (button states?)',
  },
  /* 063 0x3f */ {
    name: 'message_priority_frame',
    role: 'message_priority',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x3f CBaseToolGfxElement _priorityFrame, rect (24,0,126x41)',
  },
  /* 064 0x40 */ {
    name: 'message_priority_button',
    role: 'message_priority',
    palette: 'iconsleft',
    source: 'manual',
    states: ['message_priority_button_important', 'message_priority_button_only_important'],
    note: 'gfx 0x40 _btnPriority, rect (106,3,37x31), msg 0xf47, tooltip str 0x0E; priority mode 0',
  },
  /* 065 0x41 */ {
    name: 'message_priority_button_important',
    role: 'message_priority',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x41, priority mode 1 (hide unimportant)',
  },
  /* 066 0x42 */ {
    name: 'message_priority_button_only_important',
    role: 'message_priority',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x42, priority mode 2 (only important)',
  },
  /* 067 0x43 */ {
    name: 'unknown_067',
    role: 'note',
    palette: 'papyrus',
    source: 'montage',
    note: 'parchment note / scroll 54x69 (coloured pin)',
  },
  /* 068 0x44 */ {
    name: 'unknown_068',
    role: 'note',
    palette: 'papyrus',
    source: 'montage',
    note: 'parchment note / scroll 54x69 (coloured pin)',
  },
  /* 069 0x45 */ {
    name: 'unknown_069',
    role: 'note',
    palette: 'papyrus',
    source: 'montage',
    note: 'parchment note / scroll 54x69 (coloured pin)',
  },
  /* 070 0x46 */ {
    name: 'unknown_070',
    role: 'window_bg',
    palette: 'papyrus',
    source: 'montage',
    note: 'papyrus window background 516x339',
  },
  /* 071 0x47 */ {
    name: 'unknown_071',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small dark frame / box',
  },
  /* 072 0x48 */ {
    name: 'unknown_072',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 073 0x49 */ {
    name: 'unknown_073',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 074 0x4a */ {
    name: 'unknown_074',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 075 0x4b */ {
    name: 'unknown_075',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 076 0x4c */ {
    name: 'unknown_076',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'leaf / herb (stone token)',
  },
  /* 077 0x4d */ {
    name: 'unknown_077',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'cow / livestock (stone token)',
  },
  /* 078 0x4e */ {
    name: 'unknown_078',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'sprout / plant (stone token)',
  },
  /* 079 0x4f */ {
    name: 'unknown_079',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'plate / meal (stone token)',
  },
  /* 080 0x50 */ {
    name: 'unknown_080',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 081 0x51 */ {
    name: 'unknown_081',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'teapot (stone token)',
  },
  /* 082 0x52 */ {
    name: 'unknown_082',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 083 0x53 */ {
    name: 'unknown_083',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 084 0x54 */ {
    name: 'unknown_084',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'gold bars / ingots (stone token)',
  },
  /* 085 0x55 */ {
    name: 'unknown_085',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'wheat / grain (stone token)',
  },
  /* 086 0x56 */ {
    name: 'unknown_086',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'tree / wood (stone token)',
  },
  /* 087 0x57 */ {
    name: 'unknown_087',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'skull & crossbones (stone token) — attack/death?',
  },
  /* 088 0x58 */ {
    name: 'unknown_088',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'handshake (stone token) — trade/diplomacy?',
  },
  /* 089 0x59 */ {
    name: 'unknown_089',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'house + ladder (stone token) — build?',
  },
  /* 090 0x5a */ {
    name: 'unknown_090',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'crossed swords (stone token) — military/attack?',
  },
  /* 091 0x5b */ {
    name: 'unknown_091',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'chest / goods (stone token)',
  },
  /* 092 0x5c */ {
    name: 'unknown_092',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'fish / food (stone token)',
  },
  /* 093 0x5d */ {
    name: 'unknown_093',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'leather / hide (stone token)',
  },
  /* 094 0x5e */ {
    name: 'unknown_094',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'armor / chainmail (stone token)',
  },
  /* 095 0x5f */ {
    name: 'unknown_095',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'engraved stone/stamp command-or-resource token (context palette)',
  },
  /* 096 0x60 */ {
    name: 'order_build',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: hammer; provisional name pending exact command',
  },
  /* 097 0x61 */ {
    name: 'order_worker',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: figure with crossed tools; provisional name pending exact command',
  },
  /* 098 0x62 */ {
    name: 'order_move',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: walking figure; provisional name pending exact command',
  },
  /* 099 0x63 */ {
    name: 'order_query',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: question mark in dotted ring; provisional name pending exact command',
  },
  /* 100 0x64 */ {
    name: 'order_attention',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: exclamation in dotted ring; provisional name pending exact command',
  },
  /* 101 0x65 */ {
    name: 'order_house_enter',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: house with door/key; provisional name pending exact command',
  },
  /* 102 0x66 */ {
    name: 'order_cancel_attack',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords with X; provisional name pending exact command',
  },
  /* 103 0x67 */ {
    name: 'order_build_house',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: hammer + house; provisional name pending exact command',
  },
  /* 104 0x68 */ {
    name: 'order_marry',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: two interlocked rings; provisional name pending exact command',
  },
  /* 105 0x69 */ {
    name: 'order_male',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: male symbol; provisional name pending exact command',
  },
  /* 106 0x6a */ {
    name: 'order_female',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: female symbol; provisional name pending exact command',
  },
  /* 107 0x6b */ {
    name: 'order_icon_fallback',
    role: 'order_icon',
    palette: 'context',
    source: 'manual',
    note: 'gfx 0x6b default order/command icon; round wooden button using the context palette',
  },
  /* 108 0x6c */ {
    name: 'unknown_108',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden command/action-order button (context palette); glyph: two angled zigzag/lightning tools',
  },
  /* 109 0x6d */ {
    name: 'order_eat',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: fork + knife; provisional name pending exact command',
  },
  /* 110 0x6e */ {
    name: 'order_alert',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: exclamation mark; provisional name pending exact command',
  },
  /* 111 0x6f */ {
    name: 'order_mine',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: "round wooden order button (context palette); glyph: pickaxe; user-identified as the scout's Erect Signpost order button",
  },
  /* 112 0x70 */ {
    name: 'order_change_profession',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette); glyph: two screws (one larger, one smaller) — user-identified as the "change profession" command; provisional name pending exact command',
  },
  /* 113 0x71 */ {
    name: 'order_repair',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: wrench; provisional name pending exact command',
  },
  /* 114 0x72 */ {
    name: 'order_soldier_1',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords "1"; provisional name pending exact command',
  },
  /* 115 0x73 */ {
    name: 'order_soldier_2',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords "2"; provisional name pending exact command',
  },
  /* 116 0x74 */ {
    name: 'order_soldier_3',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords "3"; provisional name pending exact command',
  },
  /* 117 0x75 */ {
    name: 'order_soldier_4',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords "4"; provisional name pending exact command',
  },
  /* 118 0x76 */ {
    name: 'order_spearman',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: figure with spear; provisional name pending exact command',
  },
  /* 119 0x77 */ {
    name: 'order_house',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: house; provisional name pending exact command',
  },
  /* 120 0x78 */ {
    name: 'order_animal',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: dog / animal; provisional name pending exact command',
  },
  /* 121 0x79 */ {
    name: 'order_transport',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: wheelbarrow + animal; provisional name pending exact command',
  },
  /* 122 0x7a */ {
    name: 'order_animal_2',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: dog / animal (variant); provisional name pending exact command',
  },
  /* 123 0x7b */ {
    name: 'order_assign_work',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: tools + checkmark; provisional name pending exact command',
  },
  /* 124 0x7c */ {
    name: 'order_cancel',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: X; provisional name pending exact command',
  },
  /* 125 0x7d */ {
    name: 'order_figure_hand',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: figure + raised hand; provisional name pending exact command',
  },
  /* 126 0x7e */ {
    name: 'order_pray',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: praying hands; provisional name pending exact command',
  },
  /* 127 0x7f */ {
    name: 'order_crest',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: ornate heraldic crest; provisional name pending exact command',
  },
  /* 128 0x80 */ {
    name: 'order_cancel_build',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed hammers with X; provisional name pending exact command',
  },
  /* 129 0x81 */ {
    name: 'order_house_repair',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: hammer + house (variant); provisional name pending exact command',
  },
  /* 130 0x82 */ {
    name: 'order_cancel_attack_2',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords with X (variant); provisional name pending exact command',
  },
  /* 131 0x83 */ {
    name: 'order_justice',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: scales + sword; provisional name pending exact command',
  },
  /* 132 0x84 */ {
    name: 'order_cancel_2',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: X (variant); provisional name pending exact command',
  },
  /* 133 0x85 */ {
    name: 'order_cancel_attack_3',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: crossed swords with X (variant); provisional name pending exact command',
  },
  /* 134 0x86 */ {
    name: 'order_construct',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: hammer / pickaxe; provisional name pending exact command',
  },
  /* 135 0x87 */ {
    name: 'order_machinery',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: ring of gears; provisional name pending exact command',
  },
  /* 136 0x88 */ {
    name: 'order_scout',
    role: 'order_icon',
    palette: 'context',
    source: 'montage',
    note: 'round wooden order button (context palette), user-confirmed order/command icon; glyph: eye with rays; provisional name pending exact command',
  },
  /* 137 0x89 */ {
    name: 'unknown_137',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'gold nugget / ore (or small chest)',
  },
  /* 138 0x8a */ {
    name: 'unknown_138',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow (up/down/left/right, green field)',
  },
  /* 139 0x8b */ {
    name: 'unknown_139',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow (up/down/left/right, green field)',
  },
  /* 140 0x8c */ {
    name: 'unknown_140',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow (up/down/left/right, green field)',
  },
  /* 141 0x8d */ {
    name: 'unknown_141',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow (up/down/left/right, green field)',
  },
  /* 142 0x8e */ {
    name: 'unknown_142',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'gem / gold diamond 16x14',
  },
  /* 143 0x8f */ {
    name: 'unknown_143',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small tab / bookmark 9x14',
  },
  /* 144 0x90 */ {
    name: 'unknown_144',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'target / crosshair ring 9x9',
  },
  /* 145 0x91 */ {
    name: 'overview_toggle_button',
    role: 'overview_toggle',
    palette: 'iconsleft',
    source: 'manual',
    note: 'gfx 0x91 _overviewToggleButton, rect (0,TopBarY-38,38x38), msg 0x0f45, tooltip str 0x0C "opens overview map"; code palette is TopBarPalette (iconsleft is a best-guess default)',
  },
  /* 146 0x92 */ {
    name: 'unknown_146',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: cow / livestock',
  },
  /* 147 0x93 */ {
    name: 'unknown_147',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: teapot',
  },
  /* 148 0x94 */ {
    name: 'unknown_148',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon ~20x18',
  },
  /* 149 0x95 */ {
    name: 'unknown_149',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: plate / meal',
  },
  /* 150 0x96 */ {
    name: 'resource_icon_herb',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: herb / plant (details-panel stock guess for herb/mushroom); pending the step-3 human pass',
  },
  /* 151 0x97 */ {
    name: 'unknown_151',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon ~20x18',
  },
  /* 152 0x98 */ {
    name: 'resource_icon_pickaxes',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: crossed pickaxes / mining (details-panel stock guess for iron); pending the step-3 human pass',
  },
  /* 153 0x99 */ {
    name: 'resource_icon_gold_bars',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: gold bars / ingots (details-panel stock guess for gold/coin); pending the step-3 human pass',
  },
  /* 154 0x9a */ {
    name: 'unknown_154',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: scales / balance',
  },
  /* 155 0x9b */ {
    name: 'resource_icon_tree',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small resource icon: tree / wood (details-panel stock guess for wood); pending the step-3 human pass',
  },
  /* 156 0x9c */ {
    name: 'unknown_156',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'faint small icon ~20x18 (figure + tool?)',
  },
  /* 157 0x9d */ {
    name: 'house_plate',
    role: 'window_control',
    palette: 'iconsleft',
    source: 'montage',
    note: 'house plate 42x24 (details-panel preview fallback backdrop)',
  },
  /* 158 0x9e */ {
    name: 'unknown_158',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 159 0x9f */ {
    name: 'unknown_159',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 160 0xa0 */ {
    name: 'unknown_160',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 161 0xa1 */ {
    name: 'unknown_161',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 162 0xa2 */ {
    name: 'unknown_162',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 163 0xa3 */ {
    name: 'unknown_163',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame 70x22 (decoded atlas rect) — solid fill under bar_* palettes',
  },
  /* 164 0xa4 */ {
    name: 'unknown_164',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame 70x22 (decoded atlas rect) — solid fill under bar_* palettes',
  },
  /* 165 0xa5 */ {
    name: 'bar_frame_96',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame 96x18 (decoded atlas rect) — solid fill under bar_* palettes; the details-panel progress/need bar',
  },
  /* 166 0xa6 */ {
    name: 'unknown_166',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame 96x18 (decoded atlas rect) — solid fill under bar_* palettes',
  },
  /* 167 0xa7 */ {
    name: 'unknown_167',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 168 0xa8 */ {
    name: 'unknown_168',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame (70x22 / 96x18) — solid fill under bar_* palettes',
  },
  /* 169 0xa9 */ {
    name: 'unknown_169',
    role: 'resource_icon',
    palette: 'context',
    source: 'montage',
    note: 'small goods / ornament glyph ~32x18',
  },
  /* 170 0xaa */ {
    name: 'stock_tab_0',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 171 0xab */ {
    name: 'stock_tab_1',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 172 0xac */ {
    name: 'stock_tab_2',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 173 0xad */ {
    name: 'stock_tab_3',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 174 0xae */ {
    name: 'stock_tab_4',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 175 0xaf */ {
    name: 'stock_tab_5',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 176 0xb0 */ {
    name: 'stock_tab_6',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 177 0xb1 */ {
    name: 'stock_tab_7',
    role: 'resource_icon',
    palette: 'bg_invert',
    source: 'montage',
    note: 'stock-window category tab 32x18: renders through the bg_invert palette as a BRIGHT cream line-art glyph on a recessed plate (our palette choice, not decoded frame semantics — context rendered it dark-on-dark); eight-tab strip, per-tab category unread — pending the step-3 human pass',
  },
  /* 178 0xb2 */ {
    name: 'unknown_178',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'gold ornament badge 24x39 (vertical)',
  },
  /* 179 0xb3 */ {
    name: 'unknown_179',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'exchange / swap arrows 39x30',
  },
  /* 180 0xb4 */ {
    name: 'unknown_180',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'chain / infinity link 15x8',
  },
  /* 181 0xb5 */ {
    name: 'unknown_181',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small ornament / creature glyph (NOT a mouse cursor — cursors are separate .cur files)',
  },
  /* 182 0xb6 */ {
    name: 'unknown_182',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small ornament / creature glyph (NOT a mouse cursor — cursors are separate .cur files)',
  },
  /* 183 0xb7 */ {
    name: 'unknown_183',
    role: 'decoration',
    palette: 'iconsleft',
    source: 'montage',
    note: 'small ornament / creature glyph (NOT a mouse cursor — cursors are separate .cur files)',
  },
  /* 184 0xb8 */ {
    name: 'unknown_184',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'orange directional arrow 25x23 (left/right)',
  },
  /* 185 0xb9 */ {
    name: 'unknown_185',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'orange directional arrow 25x23 (left/right)',
  },
  /* 186 0xba */ {
    name: 'unknown_186',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 187 0xbb */ {
    name: 'unknown_187',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 188 0xbc */ {
    name: 'unknown_188',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 189 0xbd */ {
    name: 'unknown_189',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 190 0xbe */ {
    name: 'unknown_190',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 191 0xbf */ {
    name: 'unknown_191',
    role: 'scroll_arrow',
    palette: 'context',
    source: 'montage',
    note: 'directional arrow cluster (map-edge scroll / compass rose?)',
  },
  /* 192 0xc0 */ {
    name: 'unknown_192',
    role: 'bar',
    palette: 'bar_standart',
    source: 'montage',
    note: 'horizontal bar frame 96x18 — solid fill under bar_* palettes',
  },
];

/**
 * Ergonomic named constants for the code-pinned frames app HUD code references, so it never hardcodes an
 * index (e.g. `GUI_FRAME.tool_button_buildings`). Kept in lock-step with {@link GUI_FRAMES} by the test.
 * Unidentified frames are addressed via {@link guiFrameIndex} once promoted from `unknown_NNN`.
 */
export const GUI_FRAME = {
  knot_corner_bl: 0,
  knot_corner_br: 1,
  knot_corner_tl: 2,
  knot_corner_tr: 3,
  window_border_bottom: 5,
  window_border_right: 6,
  window_border_top: 7,
  window_border_left: 8,
  resource_icon_dark_lump: 29,
  resource_icon_round_stone: 30,
  tool_button_buildings: 42,
  tool_button_population: 43,
  tool_button_diplomacy: 44,
  tool_button_extras: 45,
  tool_button_mission: 46,
  tool_button_options: 47,
  tool_button_help: 48,
  speed_button: 49,
  tool_button_statistics: 50,
  tool_panel_background: 51,
  speed_button_x2: 52,
  speed_button_x3: 53,
  speed_button_paused: 54,
  minimap_frame: 55,
  tool_button_tech_tree: 56,
  message_priority_frame: 63,
  message_priority_button: 64,
  message_priority_button_important: 65,
  message_priority_button_only_important: 66,
  order_icon_fallback: 107,
  overview_toggle_button: 145,
  resource_icon_herb: 150,
  resource_icon_pickaxes: 152,
  resource_icon_gold_bars: 153,
  resource_icon_tree: 155,
  house_plate: 157,
  bar_frame_96: 165,
  stock_tab_0: 170,
} as const;

/** The stock window's eight-tab strip: `stock_tab_0`..`stock_tab_7` are consecutive frames on the sheet. */
export const STOCK_TAB_COUNT = 8;

/** Reverse lookup name -> frame index, built once from {@link GUI_FRAMES}. */
const FRAME_INDEX_BY_NAME: ReadonlyMap<string, number> = new Map(
  GUI_FRAMES.map((f, i) => [f.name, i] as const),
);

/**
 * Frame index for a semantic name. Throws (programmer error) on an unknown name — callers use compile-time
 * constants ({@link GUI_FRAME}) or names verified against {@link GUI_FRAMES}, so a miss means a typo/stale ref.
 */
export function guiFrameIndex(name: string): number {
  const i = FRAME_INDEX_BY_NAME.get(name);
  if (i === undefined) throw new Error(`gui-atlas-map: no frame named "${name}"`);
  return i;
}
