/**
 * The installer's English catalog — the source of truth for the message shape (`pl.ts` is checked
 * against the derived {@link Messages} type). Kept to the game's i18n conventions
 * (`packages/app/src/i18n`) deliberately, though the two catalogs stay separate: the installer is a
 * Node + own-renderer surface that runs before any game content exists, so it cannot reuse the
 * browser-only game catalog behind the `app://` boundary.
 *
 * The three `*Html` entries carry trusted developer markup (`<em>`/`<code>`/`<strong>`) and are set
 * as innerHTML; they never interpolate user input.
 */
export const en = {
  setup: {
    title: 'Open Northland — first-run setup',
    introHtml:
      'Open Northland is a free re-implementation of <em>Cultures — 8th Wonder of the World</em>. It ' +
      'ships no game art or sounds: on this first run it converts the assets of your own copy of the ' +
      'original game into its data folder. Select the folder your game is installed in (the one with ' +
      '<code>Game.exe</code> and <code>DataX</code>) to begin.',
    pathPlaceholder: 'Path to your Cultures 8th Wonder folder…',
    browse: 'Browse…',
    detected: 'Found on this computer:',
    install: 'Install game content',
    regenerate: 'Regenerate game content',
    play: 'Play',
    playAnyway: 'Play anyway',
    cancel: 'Cancel',
    back: 'Back',
    installed: 'Game content installed.',
    legalHtml:
      'Your original game files are only read, never modified. The converted data stays on this ' +
      'computer in <code id="data-root"></code>.',
    probe: {
      withMod: 'Game found (with the culturesnation mod).',
      externalMod: 'Game found. Using the CulturesNation mod from {path}.',
      noMod: 'Game found — but the CulturesNation mod is missing.',
      noArchives: 'No game archives (.lib) found there — pick the folder that contains Game.exe and DataX.',
    },
    status: {
      ready: 'Game content is installed. Regenerate it here if you want a fresh conversion.',
      staleRevision:
        'Your game content is incomplete or was generated by an older version of Open Northland — ' +
        'regenerating it is recommended.',
      staleSchema:
        'Your game content was generated by an incompatible older version of Open Northland — it must ' +
        'be regenerated before playing.',
    },
    run: {
      starting: 'Starting…',
      files: '{done} files',
      failed: 'Installing the game content failed.',
    },
    stages: {
      unpack: 'Unpacking game archives',
      pictures: 'Converting pictures',
      atlases: 'Building sprite atlases',
      'player-colors': 'Building player colours',
      gui: 'Converting the interface art',
      fonts: 'Converting fonts',
      goods: 'Converting goods icons',
      ir: 'Extracting game rules',
      transitions: 'Composing terrain transitions',
      maps: 'Decoding maps',
    },
    mod: {
      requiredHtml:
        'The free community mod <strong>CulturesNation</strong> is required to play, and your game ' +
        'folder does not have it. Open Northland can download it for you (~600 MB, from ' +
        "<code>culturesnation.pl</code>'s Google Drive link) into its data folder — your game folder " +
        'stays untouched.',
      download: 'Download the mod',
      haveIt: 'I already have it…',
      downloading: 'Downloading the mod…',
      unpacking: 'Unpacking…',
      cancelled: 'Download cancelled.',
      downloadFailed: 'Downloading the mod failed: {message} — {fallback}',
      pickFailed: '{message} — {fallback}',
      fallbackNote:
        'You can download the mod yourself from culturesnation.pl (news page → CnMod), unpack the zip, ' +
        'and point "I already have it…" at the unpacked folder.',
    },
    language: {
      english: 'English',
      polish: 'Polish',
    },
  },
  dialogs: {
    pickGameTitle: 'Select your Cultures - 8th Wonder of the World folder',
    pickModTitle: 'Select the unpacked CulturesNation mod folder',
    leaveGame: 'Leave game',
    stay: 'Stay',
    leaveGameMessage: 'Leave the running game?',
    leaveGameDetail: 'There is no saving yet — the current session will be lost.',
  },
  menu: {
    game: 'Game',
    reinstall: 'Reinstall game content…',
    openDataFolder: 'Open data folder',
  },
  errors: {
    modStillDownloading: 'the mod is still downloading — wait for it to finish',
    noArchives: 'no game archives (.lib) found under the selected folder',
    modRequired:
      'the culturesnation mod is required — download it below, or point the wizard at an unpacked copy',
    modDownloadRunning: 'mod download already running',
    noDataCnmd: 'no DataCnmd/ found there — pick the unpacked mod folder (download it from {url})',
    incompatibleSchema: 'content was generated for an incompatible schema — regenerate it first',
  },
} as const;

type DeepStrings<T> = { readonly [K in keyof T]: T[K] extends string ? string : DeepStrings<T[K]> };

export type Messages = DeepStrings<typeof en>;
