import type { DesktopApi, DesktopState, GameFolderCandidate } from '../ipc.js';
import { el } from './dom.js';
import { renderModEvent, wireModPanel } from './mod-panel.js';
import { createPipelineProgress } from './pipeline-progress.js';

/**
 * The first-run installer page. Phases: pick (path input + browse + auto-detected candidates) →
 * run (progress bar + stage line + log tail) → done | failed. All game-folder knowledge lives
 * behind `window.desktop` ({@link DesktopApi}); this file is DOM glue only.
 */

declare global {
  interface Window {
    readonly desktop: DesktopApi;
  }
}

/** Pause after the last keystroke before probing the typed path — one probe per pause, not per key. */
const PROBE_DEBOUNCE_MS = 300;

const phases = { pick: el('pick'), run: el('run'), done: el('done'), failed: el('failed') } as const;
const pathInput = el<HTMLInputElement>('game-path');
const probeNote = el('probe-note');
const installButton = el<HTMLButtonElement>('install');

function showPhase(name: keyof typeof phases): void {
  for (const [key, section] of Object.entries(phases)) {
    section.classList.toggle('hidden', key !== name);
  }
}

const progress = createPipelineProgress(showPhase);

let validPath: string | undefined;
let candidateHasMod = false;
/** A mod root outside the game folder (downloaded into the data root, or hand-picked). */
let externalModRoot: string | undefined;

/** Re-word the probe note + install/mod-panel visibility for the current game/mod availability. */
function applyModAvailability(): void {
  const modPanel = el('mod-panel');
  if (validPath === undefined) {
    modPanel.classList.add('hidden');
    return;
  }
  if (candidateHasMod) {
    probeNote.textContent = 'Game found (with the culturesnation mod).';
  } else if (externalModRoot !== undefined) {
    probeNote.textContent = `Game found. Using the CulturesNation mod from ${externalModRoot}.`;
  } else {
    probeNote.textContent = 'Game found — but the CulturesNation mod is missing.';
  }
  const modReady = candidateHasMod || externalModRoot !== undefined;
  modPanel.classList.toggle('hidden', modReady);
  installButton.disabled = !modReady;
}

/** `fillInput` is off when the probe echoes what the user is typing — never fight the caret. */
function applyCandidate(candidate: GameFolderCandidate, fillInput = true): void {
  if (fillInput) pathInput.value = candidate.path;
  if (candidate.probe.hasArchives) {
    validPath = candidate.path;
    candidateHasMod = candidate.probe.hasMod;
    applyModAvailability();
  } else {
    validPath = undefined;
    probeNote.textContent =
      'No game archives (.lib) found there — pick the folder that contains Game.exe and DataX.';
    installButton.disabled = true;
    applyModAvailability();
  }
}

let probeGeneration = 0;

async function probeTyped(): Promise<void> {
  const generation = ++probeGeneration;
  const typed = pathInput.value.trim();
  if (typed === '') {
    validPath = undefined;
    probeNote.textContent = '';
    installButton.disabled = true;
    applyModAvailability(); // hides a mod panel left over from the previous candidate
    return;
  }
  const candidate = await window.desktop.probeGamePath(typed);
  if (generation !== probeGeneration) return; // a newer keystroke's probe is already in flight
  applyCandidate(candidate, false);
}

/** Word the pick phase for the content status: first install vs recommended vs required regeneration. */
function applyContentStatus(status: DesktopState['contentStatus']): void {
  if (status === 'missing') return;
  const note = el('status-note');
  const playNow = el<HTMLButtonElement>('play-now');
  note.classList.remove('hidden');
  el('install').textContent = 'Regenerate game content';
  switch (status) {
    case 'ready':
      note.textContent = 'Game content is installed. Regenerate it here if you want a fresh conversion.';
      playNow.classList.remove('hidden');
      return;
    case 'stale-revision':
      // Also the face of an interrupted conversion (no stamp survives one), hence "incomplete".
      note.textContent =
        'Your game content is incomplete or was generated by an older version of Open Northland — regenerating it is recommended.';
      playNow.textContent = 'Play anyway';
      playNow.classList.remove('hidden');
      return;
    case 'stale-schema':
      note.textContent =
        'Your game content was generated by an incompatible older version of Open Northland — it must be regenerated before playing.';
      note.classList.add('blocking');
      return;
    default: {
      const exhaustive: never = status;
      throw new Error(`unhandled content status ${JSON.stringify(exhaustive)}`);
    }
  }
}

async function boot(): Promise<void> {
  const state = await window.desktop.getState();
  el('data-root').textContent = state.dataRoot;
  applyContentStatus(state.contentStatus);
  externalModRoot = state.modRoot;
  if (state.gamePath !== undefined) {
    applyCandidate(await window.desktop.probeGamePath(state.gamePath));
  }
  window.desktop.onPipelineEvent((event) => progress.handleEvent(event));
  window.desktop.onModEvent(renderModEvent);
  wireModPanel((root) => {
    externalModRoot = root;
    applyModAvailability();
  });

  const detected = await window.desktop.detectGameFolders();
  if (detected.length > 0) {
    el('detected').classList.remove('hidden');
    const list = el('detected-list');
    for (const candidate of detected) {
      const button = document.createElement('button');
      button.type = 'button';
      button.textContent = candidate.path;
      button.addEventListener('click', () => applyCandidate(candidate));
      list.appendChild(button);
    }
  }

  el('browse').addEventListener('click', async () => {
    const picked = await window.desktop.pickGameFolder();
    if (picked !== null) applyCandidate(picked);
  });
  let probeTimer: number | undefined;
  pathInput.addEventListener('input', () => {
    window.clearTimeout(probeTimer);
    probeTimer = window.setTimeout(() => void probeTyped(), PROBE_DEBOUNCE_MS);
  });
  el('install').addEventListener('click', async () => {
    if (validPath === undefined) return;
    progress.reset();
    showPhase('run');
    try {
      await window.desktop.runPipeline(validPath);
    } catch (err) {
      progress.handleEvent({ kind: 'error', message: err instanceof Error ? err.message : String(err) });
    }
  });
  el('cancel').addEventListener('click', async () => {
    // stop() silences the run's events, so no late error flips the page to the failed phase.
    await window.desktop.stopPipeline();
    showPhase('pick');
  });
  el('play').addEventListener('click', () => void window.desktop.startGame());
  el('play-now').addEventListener('click', () => void window.desktop.startGame());
  el('retry').addEventListener('click', () => showPhase('pick'));
}

void boot();
