import type { MissionGoalOp, MissionResultOp } from './script.js';

/**
 * The goal opcodes this build evaluates. The switch in `check.ts` is the implementation; this list is
 * what the coverage report and the opcode-support test read, and the test holds the two together.
 */
export const SUPPORTED_GOALS = [
  'True',
  'TimeGone',
  'RandomTimeGone',
  'IfMissionIsActive',
  'CheckMission',
  'IsMissionDone',
  'BuildHumans',
  'BuildHouses',
  'HumansDied',
  'HousesDied',
  'AnimalsDied',
  'NumberOfHumansDied',
  'SoldiersDied',
  'NumberOfHumansKilled',
  'Population',
  'NumberOfSoldiers',
  'HumansWithHome',
  'CheckHumanJob',
  'HumanAttachedToWorkHouse',
  'FindPosByHumans',
  'FindPosByPlayersMapMoveable',
  'FindHumansByHumans',
  'FindHumansByPlayersMM',
  'FindHousesByHumans',
  'NumberOfSoldiersNearPos',
  'NumberOfCivilainsNearPos',
  'NumberOfHousesInArea',
  'NumberOfAnimalsInArea',
  'GoodsInHouses',
  'GoodsGlobal',
  'NumberOfGoodsInArea',
  'NumberOfGoodsInHousesInArea',
  'JobEnabled',
  'GoodProduceable',
  'FindPos',
  'FindHumans',
  'FindHouses',
  'FindAnimals',
  'PlayerDied',
  'DiplomacyState',
  'PlayerSeen',
  'PlayerAttackedByPlayer',
] as const satisfies readonly MissionGoalOp['opcode'][];

/** The result opcodes this build executes; see {@link SUPPORTED_GOALS}. */
export const SUPPORTED_RESULTS = [
  'None',
  'ActivateMission',
  'DeactivateMission',
  'DisableAll',
  'SetVisible',
  'Exit',
  'SetHuman',
  'SetHumanX',
  'SetAnimal',
  'SetHouse',
  'SetHouseExtensionLevel',
  'RemoveHumans',
  'RemoveAnimals',
  'RemoveHouses',
  'ChangeHumanPlayerId',
  'ChangeHousesPlayerId',
  'ChangePlayerPlayerId',
  'ChangePlayerIdInArea',
  'ChangeAnimalPlayerIdInArea',
  'ChangeMissionIdOfPlayer',
  'ChangeMissionIdOfHumanInRange',
  'ChangeHumanObjectIdInArea',
  'SendHuman',
  'MoveHuman',
  'MoveUnitsInArea',
  'StopHumanByPlayerId',
  'RemoveHumansNearPos',
  'HealHumansInArea',
  'RemoveHPsOfHousesInArea',
  'RemoveHPsOfHousesInAreaX',
  'SetHumanBehaviourFlag',
  'SetPlayerBehaviourFlag',
  'SetImportHumanFlag',
  'SetHouseBehaviourFlag',
  'AddGoodsToHouses',
  'AddGoodsToAnyStock',
  'AddGoodsToMapArea',
  'RemoveGoodsFromMapArea',
  'AllowJob',
  'EnableJob',
  'AllowHouse',
  'EnableHouse',
  'AllowGood',
  'EnableGood',
  'SetDiplomacy',
  'SetDiplomacyNotChangeableFlag',
  'MissionWon',
  'MissionFailed',
  'ExploreArea',
  'SetExternalFlag',
] as const satisfies readonly MissionResultOp['opcode'][];
